[build.env]
passthrough = ["RUSTFLAGS", "RUST_BACKTRACE", "RUST_LOG"]

[target.aarch64-unknown-linux-gnu]
image = "build_ladder_aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-musl]
image = "build_ladder_aarch64-unknown-linux-musl"

[target.x86_64-unknown-linux-gnu]
image = "build_ladder_x86_64-unknown-linux-gnu"
