log:
  level: debug

inbounds:
  - addr: 127.0.0.1:10000
    protocol: socks5

outbounds:
  - tag: ws
    protocol: vmess
    addr: 127.0.0.1:11000
    id: "27848739-7e62-4138-9fd3-098a63964b6b"
    sec: aes-128-gcm
    transport:
      type: browser
      path: "/27848739-7e62-4138-9fd3-098a63964b6b"
      command_addr: 127.0.0.1:12345
      command_path: "/helloworld"
