# *****
# Please DO NOT use any key or password shown in this file
# in your environment.
# ****

[log]
level = "info"

[[inbounds]]
addr = "0.0.0.0:40080"
protocol = "http"
    # Authentication.
    # Comment these if you want no authentication.
    [inbounds.users]
    username1 = "password1"
    username2 = "password2"
    username3 = "password3"

[[outbounds]]
protocol = "freedom"

# Block all connections going to LAN
[[router.rules]]
dst = [
    "192.168.0.0/16",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "127.0.0.0/8",
    "lan",
    "localhost",
]
outbound_tag = "$blocked"
