# *****
# Please DO NOT use any key or password shown in this file
# in your environment.
# ****

# Shadowsocks entrance.
[[inbounds]]
addr = "0.0.0.0:33333"
protocol = "shadowsocks"
method = "aes-128-gcm"
password = "password-here"

# Direct exit.
[[outbounds]]
protocol = "freedom"

# Block connections to localhost or LAN.
[[router.rules]]
dst = [
    "192.168.0.0/16",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "127.0.0.0/8",
    "lan",
    "localhost",
]
outbound_tag = "$blocked"
