# *****
# Please DO NOT use any key or password shown in this file
# in your environment.
# ****

[[inbounds]]
addr = "0.0.0.0:1080"
protocol = "socks5"
# Should UDP be enabled, false by defualt.
# `use-udp` feature must be enabled to use UDP for SOCKS5 inbound.
is_udp_enabled = false
# Authentication.
# Uncomment these if you want authentication.
# ```
# [inbounds.users]
# username1 = "password1"
# username2 = "password2"
# username3 = "password3"
# ```

[[outbounds]]
protocol = "freedom"

# Block all connections going to LAN.
[[router.rules]]
dst = [
    "192.168.0.0/16",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "127.0.0.0/8",
    "lan",
    "localhost",
]
outbound_tag = "$blocked"