# *****
# Please DO NOT use any key or password shown in this file
# in your environment.
# ****

# HTTP proxy entrance.
[[inbounds]]
addr = "127.0.0.1:1081"
protocol = "http"

# SOCKS5 proxy entrance.
[[inbounds]]
addr = "127.0.0.1:1080"
protocol = "socks5"

# Trojan proxy exit.
[[outbounds]]
addr = "server-address.com:443"
protocol = "trojan"
password = "password-here"
    [outbounds.transport]
    type = "tls"
    alpns = ["h2", "http/1.1"]

# Direct exit for all LAN connections.
[[outbounds]]
tag = "direct"
protocol = "freedom"

# Let connections to localhost or LAN bypass proxy.
[[router.rules]]
dst = [
    "192.168.0.0/16",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "127.0.0.0/8",
    "lan",
    "localhost",
]
outbound_tag = "direct"